/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campus_placement_pravesh;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PR1VESH
 */
public class Show_All extends javax.swing.JFrame {

    /**
     * Creates new form Show_All
     */
    public Show_All() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnshow = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnback1 = new javax.swing.JButton();
        btnshowhigh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sid", "FIrst Name", "Last Name", "Percentage", "aptitude", "Stream", "Phone", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnshow.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnshow.setForeground(new java.awt.Color(153, 0, 153));
        btnshow.setText("Show all Student ");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnback1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnback1.setForeground(new java.awt.Color(0, 102, 102));
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        btnshowhigh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnshowhigh.setForeground(new java.awt.Color(153, 0, 153));
        btnshowhigh.setText("Show by higher percentage ");
        btnshowhigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowhighActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnback1)
                .addGap(424, 424, 424)
                .addComponent(btnshow)
                .addGap(64, 64, 64)
                .addComponent(btnshowhigh)
                .addContainerGap(582, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(755, 755, 755)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(755, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnshow)
                    .addComponent(btnback1)
                    .addComponent(btnshowhigh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(434, 434, 434)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(466, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
        
        
         try
         {
             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/campus?autoReconnection=true&useSSL=false","root","3400");
             Statement st = con.createStatement();
             
             
             String q,sid,fname,lname,perc,stream,apt,email,phone;
       q="select * from student";
       ResultSet rs=st.executeQuery(q);
       DefaultTableModel df=(DefaultTableModel)jTable1.getModel();//show the all value in table and Default also define also swing but ese direct assign nhi krte so use the type castmeans defalt.jtab..
       df.setRowCount(0);//no any row
       // if(rs.first())
      while(rs.next())
       {
           sid=rs.getString("sid");//first record all detail are coming reading th evalue one by one
           fname=rs.getString("firstname");
           lname=rs.getString("lastname");
           perc=rs.getString("perc");
            apt=rs.getString("apt_marks");
           stream=rs.getString("stream");
           phone=rs.getString("phone");
           email=rs.getString("email");
           String data[]={sid,fname,lname,perc,apt,stream,phone,email};
           df.addRow(data);//add
       }
         }
         catch(Exception e)
         {
             System.out.println();
         }
    }//GEN-LAST:event_btnshowActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainscreen m=new mainscreen();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        
         mainscreen m=new mainscreen();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnshowhighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowhighActionPerformed
        // TODO add your handling code here:
        
         
         try
         {
             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/campus?autoReconnection=true&useSSL=false","root","3400");
             Statement st = con.createStatement();
             
             
             String q,sid,fname,lname,perc,stream,apt,email,phone;
       q="select * from student order by perc DESC";
       ResultSet rs=st.executeQuery(q);
       DefaultTableModel df=(DefaultTableModel)jTable1.getModel();//show the all value in table and Default also define also swing but ese direct assign nhi krte so use the type castmeans defalt.jtab..
       df.setRowCount(0);//no any row
       // if(rs.first())
      while(rs.next())
       {
           sid=rs.getString("sid");//first record all detail are coming reading th evalue one by one
           fname=rs.getString("firstname");
           lname=rs.getString("lastname");
           perc=rs.getString("perc");
            apt=rs.getString("apt_marks");
           stream=rs.getString("stream");
           phone=rs.getString("phone");
           email=rs.getString("email");
           String data[]={sid,fname,lname,perc,apt,stream,phone,email};
           df.addRow(data);//add
       }
         }
         catch(Exception e)
         {
             System.out.println();
         }
    }//GEN-LAST:event_btnshowhighActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_All.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_All.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_All.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_All.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_All().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnshow;
    private javax.swing.JButton btnshowhigh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
